In [2]:
conda activate alpacaenv

Note: you may need to restart the kernel to use updated packages.

In [34]:
pip install yfinance

Collecting yfinance
  Using cached yfinance-0.1.55.tar.gz (23 kB)
Requirement already satisfied: pandas>=0.24 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from yfinance) (0.24.2)
Requirement already satisfied: numpy>=1.15 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from yfinance) (1.17.0)
Requirement already satisfied: requests>=2.20 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from yfinance) (2.24.0)
Collecting multitasking>=0.0.7
  Using cached multitasking-0.0.9.tar.gz (8.1 kB)
Requirement already satisfied: lxml>=4.5.1 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from yfinance) (4.6.1)
Requirement already satisfied: pytz>=2011k in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from pandas>=0.24->yfinance) (2020.1)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from requests>=2.20->yfinance) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from requests>=2.20->yfinance) (1.25.11)
Requirement already satisfied: six>=1.5 in c:\users\eprie\anaconda3\envs\pyvizenv\lib\site-packages (from python-dateutil>=2.5.0->pandas>=0.24->yfinance) (1.15.0)
Building wheels for collected packages: yfinance, multitasking
  Building wheel for yfinance (setup.py): started
  Building wheel for yfinance (setup.py): finished with status 'done'
  Created wheel for yfinance: filename=yfinance-0.1.55-py2.py3-none-any.whl size=22622 sha256=9e5dd2e4ac933a512568c80351a551bd544efe714ac3336451410e9b73ee4feb
  Stored in directory: c:\users\eprie\appdata\local\pip\cache\wheels\aa\8a\36\59ed4f6fbcb6100967618eeb0696046bf9777a41ac2ff1f9b9
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.9-py3-none-any.whl size=8372 sha256=db6db124c6aedb42c0aae67552f534bb9b1eff3bf5648c86aed13f03c21f41f0
  Stored in directory: c:\users\eprie\appdata\local\pip\cache\wheels\ae\25\47\4d68431a7ec1b6c4b5233365934b74c1d4e665bf5f968d363a
Successfully built yfinance multitasking
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.9 yfinance-0.1.55
Note: you may need to restart the kernel to use updated packages.

In [36]:
# Import Libraries
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import json
import panel as pn
import hvplot.pandas
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
pn.extension('plotly')
import plotly.express as px
import yfinance as yf

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

WARNING:param.panel_extension: A HoloViz extension was loaded previously. This means the extension is already initialized and the following Panel extensions could not be properly loaded: ['plotly']. If you are loading custom extensions with pn.extension(...) ensure that this is called before any other HoloViz extension such as hvPlot or HoloViews.

In [2]:
# Laod .env environment
load_dotenv()

True

In [3]:
# Pull in API Key
api_key = os.getenv("glassnode_api")
type(api_key)

str

In [4]:
# Define crypto currencies to pull
crypto_list = ["BTC", "BCH", "ETH", "LTC", "USDT", "DOGE"]

In [5]:
# Define Market URLs
price_url = 'https://api.glassnode.com/v1/metrics/market/price_usd'
volume_url = 'https://api.glassnode.com/v1/metrics/transactions/transfers_volume_sum'
mkt_cap_url = 'https://api.glassnode.com/v1/metrics/market/marketcap_usd'

# Define Demand URLs
total_addresses_url = 'https://api.glassnode.com/v1/metrics/addresses/count'
sending_addresses_url = 'https://api.glassnode.com/v1/metrics/addresses/sending_count'
receiving_addresses_url = 'https://api.glassnode.com/v1/metrics/addresses/receiving_count'
active_addresses_url = 'https://api.glassnode.com/v1/metrics/addresses/active_count'
transactions_url = 'https://api.glassnode.com/v1/metrics/transactions/count'

# Define Supply URLs
circulating_supply_url = 'https://api.glassnode.com/v1/metrics/supply/current'

# Define Mining Revenue URLs
mining_revenue_sum_url = 'https://api.glassnode.com/v1/metrics/mining/revenue_sum'

# Define Indicator URLs
rhodl_ratio_url = 'https://api.glassnode.com/v1/metrics/indicators/rhodl_ratio'

## LTC API Data Pull

In [7]:
# Price API Request
ltc_price_res = requests.get(price_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert price to Pandas Dataframe, set index to time and clean up file
ltc_price_df = pd.read_json(ltc_price_res.text, convert_dates=['t'])
ltc_price_df.columns = ['Date', 'LTC Price']
ltc_price_df.set_index('Date', inplace=True) 


# Volume API Request
ltc_volume_res = requests.get(volume_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert volume to Pandas Dataframe, set index to time and clean up file
ltc_volume_df = pd.read_json(ltc_volume_res.text, convert_dates=['t'])
ltc_volume_df.columns = ['Date', 'LTC Volume']
ltc_volume_df.set_index('Date', inplace=True)



# Market Cap API Request
ltc_mkt_cap_res = requests.get(mkt_cap_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Market Cap to Pandas Dataframe, set index to time and clean up file
ltc_mkt_cap_df = pd.read_json(ltc_mkt_cap_res.text, convert_dates=['t'])
ltc_mkt_cap_df.columns = ['Date', 'LTC Market Cap']
ltc_mkt_cap_df.set_index('Date', inplace=True)



# Mining API Request
ltc_mining_res = requests.get(mining_revenue_sum_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Mining to Pandas Dataframe, set index to time and clean up file
ltc_mining_df = pd.read_json(ltc_mining_res.text, convert_dates=['t'])
ltc_mining_df.columns = ['Date', 'LTC Mining Revenue']
ltc_mining_df.set_index('Date', inplace=True)



# # RHODL API Request
# ltc_rhodl_res = requests.get(rhodl_ratio_url,
#                       params={'a': 'LTC',
#                               'i': '24h',
#                               'api_key': api_key})


# # Convert RHODL to Pandas Dataframe, set index to time and clean up file
# ltc_rhodl_df = pd.read_json(ltc_rhodl_res.text, convert_dates=['t'])
# ltc_rhodl_df.columns = ['Date', 'LTC RHDOL Ratio']
# ltc_rhodl_df.set_index('Date', inplace=True)


# Supply API Request
ltc_supply_res = requests.get(circulating_supply_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Supply to Pandas Dataframe, set index to time and clean up file
ltc_supply_df = pd.read_json(ltc_supply_res.text, convert_dates=['t'])
ltc_supply_df.columns = ['Date', 'LTC Supply']
ltc_supply_df.set_index('Date', inplace=True)


# Total Addresses API Request
ltc_total_addresses_res = requests.get(total_addresses_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Total Addresses to Pandas Dataframe, set index to time and clean up file
ltc_total_addresses_df = pd.read_json(ltc_total_addresses_res.text, convert_dates=['t'])
ltc_total_addresses_df.columns = ['Date', 'LTC Total Addresses']
ltc_total_addresses_df.set_index('Date', inplace=True)


# Sending Addresses API Request
ltc_sending_addresses_res = requests.get(sending_addresses_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Sending Addresses to Pandas Dataframe, set index to time and clean up file
ltc_sending_addresses_df = pd.read_json(ltc_sending_addresses_res.text, convert_dates=['t'])
ltc_sending_addresses_df.columns = ['Date', 'LTC Sending Addresses']
ltc_sending_addresses_df.set_index('Date', inplace=True)


# Receiving Addresses API Request
ltc_receiving_addresses_res = requests.get(receiving_addresses_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Receiving Addresses to Pandas Dataframe, set index to time and clean up file
ltc_receiving_addresses_df = pd.read_json(ltc_receiving_addresses_res.text, convert_dates=['t'])
ltc_receiving_addresses_df.columns = ['Date', 'LTC Receiving Addresses']
ltc_receiving_addresses_df.set_index('Date', inplace=True)



# Active Addresses API Request
ltc_active_addresses_res = requests.get(active_addresses_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Active Addresses to Pandas Dataframe, set index to time and clean up file
ltc_active_addresses_df = pd.read_json(ltc_active_addresses_res.text, convert_dates=['t'])
ltc_active_addresses_df.columns = ['Date', 'LTC Active Addresses']
ltc_active_addresses_df.set_index('Date', inplace=True)



# Transactions API Request
ltc_transactions_res = requests.get(transactions_url,
                      params={'a': 'LTC',
                              'i': '24h',
                              'api_key': api_key})


# Convert Active Addresses to Pandas Dataframe, set index to time and clean up file
ltc_transactions_df = pd.read_json(ltc_transactions_res.text, convert_dates=['t'])
ltc_transactions_df.columns = ['Date','LTC Transactions']
ltc_transactions_df.set_index('Date', inplace=True)

In [21]:
# ltc_price_df.head(5)

In [22]:
# ltc_volume_df.head(5)

In [23]:
# ltc_mkt_cap_df.head(5)

In [24]:
# ltc_mining_df.head(5)

In [25]:
# ltc_rhodl_df.head(5)

In [26]:
# ltc_supply_df.head(5)

In [27]:
# ltc_total_addresses_df.head(5)

In [28]:
# ltc_sending_addresses_df.head(5)

In [29]:
# ltc_receiving_addresses_df.head(5)

In [30]:
# ltc_active_addresses_df.head(5)

In [31]:
# ltc_transactions_df.head(5)

## LTC Daily Changes

In [19]:
# Daily change in price column
ltc_daily_price_pct_change = ltc_price_df.pct_change(1)
ltc_daily_price_pct_change.columns = ['LTC Daily Price Change (%)']

# ltc_daily_price_pct_change

## LTC Data Aggregating & Cleaning

In [20]:
# # Define all the different data frames into a list
# ltc_frames = [ltc_price_df, ltc_volume_df, ltc_mkt_cap_df, ltc_mining_df]

# # Concatenate all the dataframes into one
# ltc_data = pd.concat(ltc_frames, axis=1, join="outer", ignore_index=False)
# ltc_data=ltc_data.reset_index()
# ltc_data = ltc_data.assign(Crypto='LTC')
# ltc_data

# Define all the different data frames into a list
ltc_frames = [ltc_price_df,
              ltc_daily_price_pct_change,
              ltc_volume_df,
              ltc_mkt_cap_df,
              ltc_mining_df,
              ltc_rhodl_df,
              ltc_supply_df,
              ltc_total_addresses_df,
              ltc_sending_addresses_df,
              ltc_receiving_addresses_df,
              ltc_active_addresses_df,
              ltc_transactions_df]

# Concatenate all the dataframes into one
ltc_data = pd.concat(ltc_frames, axis=1, join="outer", ignore_index=False)
ltc_data

,LTC Price,LTC Daily Price Change (%),LTC Volume,LTC Market Cap,LTC Mining Revenue,LTC Supply,LTC Total Addresses,LTC Sending Addresses,LTC Receiving Addresses,LTC Active Addresses,LTC Transactions
Date,,,,,,,,,,,
2011-10-13,NaN,NaN,4.419948e+04,NaN,484100.001000,484250.0,9777.0,849.0,110.0,919.0,92.0
2011-10-14,NaN,NaN,2.251838e+04,NaN,56100.002000,540350.0,10941.0,425.0,55.0,464.0,62.0
2011-10-15,NaN,NaN,3.068284e+04,NaN,38100.075000,578450.0,12205.0,764.0,528.0,927.0,438.0
2011-10-16,NaN,NaN,1.991927e+05,NaN,45750.907071,624250.0,14624.0,3978.0,1592.0,4271.0,1415.0
2011-10-17,NaN,NaN,9.149340e+04,NaN,38650.356248,662850.0,16975.0,2432.0,1727.0,2705.0,1578.0
2011-10-18,NaN,NaN,1.622171e+05,NaN,41300.374511,704050.0,19491.0,2962.0,1879.0,3269.0,1651.0
2011-10-19,NaN,NaN,8.609010e+04,NaN,32150.316770,736100.0,21531.0,1921.0,1596.0,2212.0,1388.0
2011-10-20,NaN,NaN,1.176173e+05,NaN,37950.317304,774250.0,24137.0,2995.0,2058.0,3303.0,1851.0
2011-10-21,NaN,NaN,9.169066e+04,NaN,41550.308110,815800.0,26651.0,2426.0,1881.0,2724.0,1681.0
2011-10-22,NaN,NaN,1.348464e+05,NaN,36400.483869,852200.0,28883.0,2081.0,1737.0,2393.0,1505.0
2011-10-23,NaN,NaN,1.283725e+05,NaN,41400.434000,893600.0,31269.0,2328.0,1793.0,2616.0,1562.0
2011-10-24,NaN,NaN,8.371506e+04,NaN,29800.339693,923400.0,33278.0,2026.0,1649.0,2308.0,1443.0
2011-10-25,NaN,NaN,9.893559e+04,NaN,26150.233000,949550.0,35049.0,1732.0,1468.0,2030.0,1260.0
2011-10-26,NaN,NaN,1.890643e+05,NaN,28850.326743,978400.0,36926.0,3573.0,1534.0,3887.0,1310.0
2011-10-27,NaN,NaN,6.736294e+04,NaN,21350.140114,999750.0,38273.0,1273.0,1111.0,1534.0,933.0
2011-10-28,NaN,NaN,9.537856e+04,NaN,22550.277030,1022300.0,40092.0,1971.0,1590.0,2284.0,1388.0
2011-10-29,NaN,NaN,1.179488e+05,NaN,29000.694478,1051300.0,42167.0,2306.0,1725.0,2614.0,1522.0
2011-10-30,NaN,NaN,1.919601e+05,NaN,36801.747996,1088100.0,44647.0,2400.0,1985.0,2750.0,1749.0
2011-10-31,NaN,NaN,4.002098e+05,NaN,33000.889135,1121100.0,47080.0,3010.0,2032.0,3348.0,1779.0
2011-11-01,NaN,NaN,4.268212e+05,NaN,43802.519152,1164900.0,49914.0,2945.0,2250.0,3363.0,1980.0
2011-11-02,NaN,NaN,1.866774e+05,NaN,61951.562273,1226850.0,53487.0,3727.0,2640.0,4143.0,2348.0
2011-11-03,NaN,NaN,1.221091e+05,NaN,45200.308827,1272050.0,56396.0,2796.0,2296.0,3198.0,2029.0
2011-11-04,NaN,NaN,1.335458e+05,NaN,46550.317207,1318600.0,59422.0,3180.0,2401.0,3574.0,2112.0
2011-11-05,NaN,NaN,9.178925e+04,NaN,29650.233546,1348250.0,61598.0,2179.0,1863.0,2560.0,1592.0
2011-11-06,NaN,NaN,8.905770e+04,NaN,31350.358120,1379600.0,63930.0,2369.0,1982.0,2740.0,1716.0
2011-11-07,NaN,NaN,9.681454e+04,NaN,29201.345096,1408800.0,66112.0,2153.0,1862.0,2521.0,1608.0
2011-11-08,NaN,NaN,1.155007e+05,NaN,26700.292686,1435500.0,68366.0,2394.0,1996.0,2760.0,1734.0
2011-11-09,NaN,NaN,9.985874e+04,NaN,27150.857641,1462650.0,70413.0,2062.0,1740.0,2401.0,1505.0
2011-11-10,NaN,NaN,8.903572e+04,NaN,26300.216066,1488950.0,72415.0,2019.0,1726.0,2388.0,1487.0
2011-11-11,NaN,NaN,1.369190e+05,NaN,28851.239689,1517800.0,75089.0,2610.0,2333.0,3037.0,2003.0
...,...,...,...,...,...,...,...,...,...,...,...
2021-02-11,184.182222,0.013308,8.660246e+06,1.238277e+10,NaN,66989925.0,66182697.0,145718.0,183691.0,215146.0,84580.0
2021-02-12,196.671635,0.067810,1.010604e+07,1.251779e+10,NaN,66997262.5,66283150.0,141076.0,189137.0,213334.0,89291.0
2021-02-13,225.968041,0.148961,1.830219e+07,1.397555e+10,NaN,67004775.0,66388974.0,154190.0,196144.0,225882.0,93307.0
2021-02-14,214.481868,-0.050831,1.646696e+07,1.472373e+10,NaN,67012112.5,66481381.0,136564.0,183960.0,208471.0,87592.0
2021-02-15,207.215852,-0.033877,1.463123e+07,1.395904e+10,NaN,67019100.0,66570291.0,125280.0,184059.0,209058.0,86643.0
2021-02-16,210.454264,0.015628,8.210361e+06,1.416881e+10,NaN,67026175.0,66652555.0,121253.0,186199.0,208975.0,87071.0
2021-02-17,236.670385,0.124569,1.689586e+07,1.483935e+10,NaN,67033300.0,66754385.0,144713.0,202140.0,232109.0,98738.0
2021-02-18,227.007952,-0.040827,3.978711e+07,1.537843e+10,NaN,67040637.5,66864792.0,176626.0,212773.0,266191.0,99239.0
2021-02-19,236.640921,0.042435,2.827413e+07,1.552980e+10,NaN,67048300.0,66976291.0,196011.0,215471.0,277172.0,101770.0
2021-02-20,227.429343,-0.038926,2.567013e+07,1.594219e+10,NaN,67055075.0,67081424.0,157130.0,213049.0,244673.0,102001.0
2021-02-21,227.366698,-0.000275,3.428362e+07,1.526842e+10,NaN,67061512.5,67172254.0,137039.0,193550.0,218579.0,89546.0
2021-02-22,208.463433,-0.083140,3.688934e+07,1.420138e+10,NaN,67068875.0,67274440.0,150927.0,212186.0,242382.0,103496.0
2021-02-23,175.137061,-0.159867,3.333707e+07,1.211542e+10,NaN,67075975.0,67376382.0,155319.0,221296.0,246799.0,102068.0
2021-02-24,181.117580,0.034148,2.291013e+07,1.217909e+10,NaN,67082812.5,67472724.0,142073.0,205993.0,229879.0,106241.0
2021-02-25,181.379308,0.001445,1.466751e+07,1.264470e+10,NaN,67089825.0,67570396.0,145839.0,206021.0,231457.0,100354.0
2021-02-26,170.069752,-0.062353,1.311784e+07,1.163356e+10,NaN,67097187.5,67674708.0,158752.0,213099.0,247362.0,114981.0
2021-02-27,172.511425,0.014357,9.064539e+06,1.173732e+10,NaN,67104500.0,67769006.0,138216.0,195744.0,219021.0,105222.0
2021-02-28,164.894918,-0.044151,2.552438e+07,1.089590e+10,NaN,67112125.0,67852639.0,120634.0,188267.0,209281.0,94734.0
2021-03-01,175.372724,0.063542,2.291548e+07,1.139775e+10,NaN,67119562.5,67946705.0,162201.0,205978.0,249460.0,101604.0
2021-03-02,177.682598,0.013171,1.534759e+07,1.183520e+10,NaN,67126962.5,68041650.0,151218.0,216600.0,247467.0,101959.0
2021-03-03,188.906064,0.063166,1.332706e+07,1.274202e+10,NaN,67133837.5,68137371.0,148667.0,209912.0,240874.0,117749.0
2021-03-04,181.000808,-0.041848,1.302336e+07,1.244476e+10,NaN,67140362.5,68240713.0,152111.0,209685.0,241753.0,99539.0
2021-03-05,180.615343,-0.002130,1.464122e+07,1.177333e+10,NaN,67147462.5,68338094.0,135587.0,211282.0,233631.0,95367.0
2021-03-06,182.979153,0.013088,8.520895e+06,1.213505e+10,NaN,67155325.0,68427820.0,126791.0,202421.0,224024.0,96671.0
2021-03-07,191.731806,0.047834,9.421075e+06,1.250725e+10,NaN,67163000.0,68512176.0,125434.0,202347.0,224493.0,90555.0
2021-03-08,192.277042,0.002844,1.122435e+07,1.256272e+10,NaN,67170575.0,68606667.0,152996.0,219588.0,250962.0,95639.0
2021-03-09,203.534055,0.058546,9.136896e+06,1.332376e+10,NaN,67177825.0,68705543.0,153515.0,235563.0,261397.0,107709.0
2021-03-10,200.728162,-0.013786,1.185928e+07,1.347717e+10,NaN,67184750.0,68809642.0,156651.0,198806.0,238485.0,115052.0
2021-03-11,200.981408,0.001262,9.790484e+06,1.334982e+10,NaN,67191537.5,68914257.0,149191.0,220234.0,245593.0,97259.0
2021-03-12,218.893385,0.089123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Reading 13wk Tbill Discount Rates

In [58]:
treasuries_discount_rate = yf.Ticker("^IRX")

In [59]:
tbills_df = yf.download("^IRX", start="2011-03-11", end="2021-03-21")

[*********************100%***********************]  1 of 1 completed

In [60]:
tbills_df=tbills_df.reset_index()
tbills_df.columns=['Date','tbills Open', 'tbills High', 'tbills Low', 'tbills Close', 'tbills Adj Close', 'tbills Volume']
tbills_df.head(5)

,Date,tbills Open,tbills High,tbills Low,tbills Close,tbills Adj Close,tbills Volume
0,2011-03-11,0.070,0.075,0.065,0.070,0.070,0
1,2011-03-14,0.070,0.080,0.065,0.075,0.075,0
2,2011-03-15,0.085,0.100,0.060,0.095,0.095,0
3,2011-03-16,0.090,0.095,0.085,0.085,0.085,0
4,2011-03-17,0.085,0.090,0.065,0.070,0.070,0

In [66]:
tbills_df=tbills_df[['Date','tbills Close']]
tbills_df.head(5)

        Date  tbills Close
0 2011-03-11         0.070
1 2011-03-14         0.075
2 2011-03-15         0.095
3 2011-03-16         0.085
4 2011-03-17         0.070